avatarium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('game/', include('game.urls'))
                  ,
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
# game/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.game, name='game'),
    path('log', views.log, name='log'),
    path('update_balance/', views.update_balance, name='update_balance'),
    path('index/', views.index, name='game-index'),
    path('quest/', views.quest, name='game-quest'),
    path('tasks/', views.tasks, name='game-tasks'),
    path('tasks/filter/', views.filter_tasks, name='filter_tasks'),
    path('tasks/create/task', views.create_task_post, name='create_task_near'),
    path('tasks/create/', views.create_task, name='create_task'),
    path('tasks/see_task/', views.task_info, name='see_task'),
    path('tasks/complete/', views.complete_task, name='complete_task'),
    path('tasks/edit_task/', views.edit_task, name='edit_task'),
    path('tasks/create/user_comment/', views.complete_task_post, name='complete_task'),
    path('tasks/info/load_images/', views.load_images, name='load_images'),
    path('tasks/update_paragraph_status/', views.update_paragraph_status, name='update_paragraph_status'),
    path('quests/see_quest/', views.quest_info, name='see_quest'),
    path('quests/complete/', views.complete_quest, name='complete_quest'),
    path('progress/', views.progress, name='progress'),
    path('progress/tasks/', views.progress_tasks, name='progress_tasks'),
    path('update_avatar/', views.update_avatar, name='update_avatar'),
    path('library/', views.library, name='library'),
    path('update_task_priority', views.update_task_priority, name='update_task_priority'),
    path('profile/', views.profile, name='profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('challenge/', views.challenge, name='challenge'),
    path('challenge/update_task_name/', views.update_task_name, name='update_task_name'),
    path('challenge/toggle_task_status/', views.toggle_task_status, name='toggle_task_status'),
    path('challenge/update_weekly_challenge/', views.update_weekly_challenge, name='update_weekly_challenge'),
    path('counter/', views.counter, name='counter'),
    path('create_counter/', views.create_counter, name='create_counter'),
    path('increment_counter/', views.increment_counter, name='increment_counter'),
    path('update_counter/', views.update_counter, name='update_counter'),
    path('delete_counter/', views.delete_counter, name='delete_counter'),

]

game/models.py
from email.policy import default

from django.db import models


class TaskCategory(models.Model):
    class Meta:
        verbose_name = 'Категория задачи'
        verbose_name_plural = 'Категории задач'

    category_name = models.CharField(max_length=255)
    title = models.CharField(max_length=255, blank=True, null=True)
    logo = models.FileField(upload_to='tasks/logos', blank=True, null=True)

    def __str__(self):
        return self.category_name


class Task(models.Model):
    title = models.CharField(max_length=25)
    cost = models.IntegerField()
    category = models.ForeignKey(
        TaskCategory,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='tasks'
    )
    top = models.BooleanField(default=False)
    far = models.BooleanField(default=False)
    post_time = models.DateField(auto_now_add=True, blank=True, null=True)
    complete_time = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title


class TaskItem(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='items')
    description = models.TextField()
    order = models.PositiveIntegerField()
    completed = models.BooleanField(default=False)

    def __str__(self):
        return f"Пункт {self.description} для задачи {self.task.title}"


class TaskComment(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE, blank=True, null=True, related_name='comment')
    user_comment = models.TextField()

    def __str__(self):
        if self.task:
            return f"Comment for {self.task.title}"
        else:
            return self.user_comment


class TaskCommentImages(models.Model):
    comment = models.ForeignKey(TaskComment, on_delete=models.CASCADE, blank=True, null=True, related_name='images')
    image = models.ImageField(upload_to='tasks/comment_images/', blank=True, null=True)

    def __str__(self):
        return f"Image for comment {self.comment.id}"


class TaskImage(models.Model):
    task = models.ForeignKey(Task, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='tasks/images/')


class Quest(models.Model):
    class Meta:
        verbose_name = 'Квест'
        verbose_name_plural = 'Квесты'

    title = models.CharField(max_length=255)
    description = models.TextField()
    sub_description = models.TextField(blank=True, null=True)
    top = models.BooleanField(default=False)
    cost = models.IntegerField()
    logo = models.FileField(upload_to='quests/logos/', blank=True, null=True)  # Поле для логотипа
    info_image = models.ImageField(upload_to='quests/images/', blank=True, null=True)  # Поле для логотипа

    def __str__(self):
        return self.title


class Users(models.Model):
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    name = models.CharField(max_length=255)
    telegram_name = models.CharField(max_length=255, blank=True, null=True)
    nickname = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(unique=True, blank=True, null=True)
    reg_time = models.DateTimeField(auto_now_add=True)
    balance = models.IntegerField(default=0)
    streak = models.IntegerField(default=0)
    week_start_date = models.DateField(null=True, blank=True)
    avatarka = models.ImageField(
        upload_to='avatars/',
        default='avatars/def_ava.png'
    )

    # Новые поля
    GENDER_CHOICES = [
        ('male', 'Мужчина'),
        ('female', 'Женщина'),
        ('attack_helicopter', 'Боевой вертолет')
    ]
    gender = models.CharField(
        max_length=20,
        choices=GENDER_CHOICES,
        blank=True,
        null=True,
        default=None
    )
    date_of_birth = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.telegram_name if self.telegram_name else self.name


class UserQuest(models.Model):
    user = models.ForeignKey(
        Users,
        on_delete=models.CASCADE,
        related_name='user_quests'
    )
    quest = models.ForeignKey(
        Quest,
        on_delete=models.CASCADE,
        related_name='user_quests_relations'
    )
    completed = models.BooleanField(default=False)

    def __str__(self):
        status = "Выполнено" if self.completed else "Не выполнено"
        return f"{self.user.name} - {self.quest.title} - {status}"


class UserTask(models.Model):
    user = models.ForeignKey(
        Users,
        on_delete=models.CASCADE,
        related_name='user_tasks_relations'
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE,
        related_name='user_tasks'
    )
    completed = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    def __str__(self):
        status = "Выполнено" if self.completed else "Не выполнено"
        active = "Активно" if self.active else "Не активно"
        return f"{self.user.name} - {self.task.title} - {status} - {active}"


class UserVisit(models.Model):
    user = models.ForeignKey(
        Users,
        on_delete=models.CASCADE,
        related_name='visits'
    )
    day_index = models.IntegerField(blank=True, null=True)

    visit_time = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.name} - {self.visit_time.strftime('%Y-%m-%d %H:%M:%S')}"


class Promo(models.Model):
    class Meta:
        verbose_name = 'Акция'
        verbose_name_plural = 'Акции'

    SHOW_PLACE_CHOICES = {
        "library": 'Библиотека',
        "main": 'Главная'
    }

    name = models.CharField(max_length=255, blank=True, null=True)
    show_place = models.CharField(
        max_length=50,
        choices=list(SHOW_PLACE_CHOICES.items()),
        default="main",
    )
    promo_img = models.FileField(upload_to='promo', blank=True, null=True)
    url = models.TextField(blank=True, null=True)

    def __str__(self):
        # Получаем русское представление значения `show_place`
        show_place_display = self.SHOW_PLACE_CHOICES.get(str(self.show_place), 'Неизвестно')
        return f"{self.name} в {show_place_display}"


# class Presentation(models.Model):
#     class Meta:
#         verbose_name = 'Слайдер'
#         verbose_name_plural = 'Слайдер'
#     promo = models.ForeignKey(Promo, null=True, blank=True, on_delete=models.CASCADE)
#
#     def __str__(self):
#         if self.promo is not None:
#             return f"Promo: {self.promo.name}"
#         return "Promo: None"

#
# class VideoUrls(models.Model):
#     class Meta:
#         verbose_name = 'Ютуб видео'
#         verbose_name_plural = 'Ютуб видео'
#     video_url = models.TextField(blank=True, null=True)
#
#     def __str__(self):
#         return "videos"


class OtherUrls(models.Model):
    class Meta:
        verbose_name = 'Дополнительные ссылки'
        verbose_name_plural = 'Дополнительные ссылки'

    post_url = models.TextField(blank=True, null=True)
    post_img = models.FileField(blank=True, null=True, upload_to='library')
    practice_url = models.TextField(blank=True, null=True)
    practice_img = models.FileField(blank=True, null=True, upload_to='library')

    def __str__(self):
        return "other"


class Questions(models.Model):
    class Meta:
        verbose_name = 'Вопрос и ответ'
        verbose_name_plural = 'Вопросы и ответы'

    question = models.CharField(max_length=255)
    answer = models.CharField(max_length=255)

    def __str__(self):
        return self.question


class UserWeeklyChallenge(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='weekly_challenges')
    week_start_date = models.DateField()
    challenge_text = models.CharField(max_length=255, blank=True, null=True)
    completed = models.BooleanField(default=False)

    monday_count = models.IntegerField(default=0)
    tuesday_count = models.IntegerField(default=0)
    wednesday_count = models.IntegerField(default=0)
    thursday_count = models.IntegerField(default=0)
    friday_count = models.IntegerField(default=0)
    saturday_count = models.IntegerField(default=0)
    sunday_count = models.IntegerField(default=0)

    class Meta:
        unique_together = ('user', 'week_start_date')

    def __str__(self):
        return f"{self.user.name} - {self.week_start_date} - {self.challenge_text}"


class UserChallengeDailyTask(models.Model):
    week = models.ForeignKey(UserWeeklyChallenge, on_delete=models.CASCADE, related_name='UserChallengeDailyTask')
    user = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='challenge_daily_tasks')
    date = models.DateField()
    task_number = models.IntegerField()  # 1..7
    title = models.CharField(max_length=255, blank=True, null=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.name} - Week: {self.week.week_start_date} - задача {self.task_number} - {('Выполнено' if self.completed else 'Не выполнено')}"


class Counter(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='counter_object')
    name = models.CharField(max_length=16)
    target = models.IntegerField()
    score = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)

game/forms.py
# forms.py
from django.forms import ModelForm, Textarea, TextInput, NumberInput, modelformset_factory, HiddenInput
from .models import Task, TaskComment, TaskItem, Counter


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'cost', 'top', 'category', 'far']
        widgets = {
            "title": TextInput(attrs={'class': 'task-title-input', 'placeholder': 'Введи название'}),
            "cost": NumberInput(attrs={'class': 'task-cost-input'}),
            "top": HiddenInput(),
            "category": HiddenInput(),
            "far": HiddenInput()
        }


class TaskItemForm(ModelForm):
    class Meta:
        model = TaskItem
        fields = ['description', 'completed']
        widgets = {
            'description': TextInput(attrs={
                'class': 'task-item-desc-input',
                'placeholder': 'Введите описание пункта',
                'maxlength': '40'
            }),
            'completed': HiddenInput()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].label = ''  # Убираем лейбл для описания


# Создание формсета для TaskItem
TaskItemFormSet = modelformset_factory(
    TaskItem,
    form=TaskItemForm,
    extra=1  # Добавляем одну пустую форму
)


class UserCommentForm(ModelForm):
    class Meta:
        model = TaskComment
        fields = ['user_comment']

        widgets = {
            "user_comment": Textarea(
                attrs={'class': 'user-comment-desc-input', 'placeholder': 'Введите текст благодарности',
                       'style': 'height: 100px;'}),

        }


class CounterForm(ModelForm):
    class Meta:
        model = Counter
        fields = ['name']

        widgets = {
            "name": TextInput(attrs={'class': 'input-counter-name', 'placeholder': 'Название счётчика'})

        }

game/templates/game/counter/counter.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Счётчики</title>
    <link rel="stylesheet" href="{% static 'game/css/counter.css' %}">
</head>
<body>
    <div class="counter-img-div">
        <img src="{% static 'game/img/counter/counter.svg' %}" class="counter-img">
        <p class="counter-title-text">Счетчик</p>
        <p class="counter-title-text-second">целей</p>

    </div>
    <div class="counter-main-div" id="counter-main-div">
        <div class="counters-list" id="counters-list">
            {% for counter in counters %}
                <div class="counter" id="counter"
                     data-counter-id="{{ counter.id }}"
                     data-counter-score="{{ counter.score }}"
                     data-counter-target="{{ counter.target }}">
                    <div class="counter-data-div">
                        <p class="counter-name">{{ counter.name }}</p>
                        <p class="counter-score">{{ counter.score }}/{{ counter.target }}</p>
                    </div>

                        <span class="increment-button">+1</span>
                    <img src="{% static 'game/img/counter/arrow.svg' %}" class="edit-button">
                </div>
            {% endfor %}
        </div>
        <div class="add-counter-div" id="add-counter-div">
            <img src="{% static 'game/img/counter/counter_circles.svg' %}" class="counter_circles">
            <p class="add-new-counter-writing">Создать новый счётчик</p>
            <img src="{% static 'game/img/tasks/plus.svg' %}" class="plus-logo">
        </div>
    </div>

    <!-- Форма создания нового счётчика -->
    <div class="counter-menu-div hidden" id="counter-menu-div">
        <div class="counter-menu-writings">
            <p class="counter-create-buttons" id="cancellation-button">Отмена</p>
            <p class="counter-create-buttons" id="create-counter-button">Готово</p>
        </div>
        <div class="counter-stats-div" id="counter-form">
            <input type="text" name="name" class="input-counter-name" placeholder="Название счётчика" maxlength="16" required id="id_name">
        </div>
        <div class="counter-stats-div-sec">
            <div class="counter-stats-line-target" id="counter-stats-line-target">
                <p class="counter-quantity">Цель</p>
                <input type="text" class="counter-quantity-input" placeholder="Количество">
            </div>
            <div class="counter-stats-line-current" id="counter-stats-line-current-create">
                <p class="counter-quantity">Счёт</p>
                <!-- Здесь значение по умолчанию (0) -->
                <p class="counter-quantity-data" id="counter-quantity-data-current-create">0</p>
            </div>
        </div>
        <div class="add-counter">
            <img src="{% static 'game/img/counter/plus_counter.svg' %}" class="remove-counter-img">
            <p class="counter-create-buttons" id="create-target-counter-button">Создать счетчик целей</p>
        </div>
    </div>

    <!-- Форма редактирования счётчика -->
    <div class="counter-menu-div hidden" id="counter-edit-menu-div">
        <div class="counter-menu-writings">
            <p class="counter-create-buttons" id="edit-cancellation-button">Отмена</p>
            <p class="counter-create-buttons" id="edit-counter-button">Готово</p>
        </div>
        <div class="counter-stats-div" id="edit-counter-form">
            <input type="text" name="name" class="input-counter-name" placeholder="Название счётчика" maxlength="16" required id="edit_id_name">
        </div>
        <div class="counter-stats-div-sec">
            <div class="counter-stats-line-target" id="edit-counter-stats-line-target">
                <p class="counter-quantity">Цель</p>
                <input type="text" class="counter-quantity-input" placeholder="Количество">
            </div>
            <div class="counter-stats-line-current" id="counter-stats-line-current-edit">
                <p class="counter-quantity">Счёт</p>
                <p class="counter-quantity-data" id="counter-quantity-data-current">0</p>
            </div>
        </div>
        <div class="remove-counter" id="remove-counter">
            <img src="{% static 'game/img/counter/remove_counter.svg' %}" class="remove-counter-img">
            <p class="remove-counter-writing">Удалить счётчик</p>
        </div>
    </div>

    <div id="content" data-csrf-token="{{ csrf_token }}"></div>

    <script src="{% static 'game/js/counter.js' %}"></script>
</body>
</html>